name = "DS9ui"
uuid = "03da5ba1-8776-4371-889c-f445af0a490c"
authors = ["Marco Lombardi <marco.lombardi@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
